name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git
          useradd -m -s /bin/bash -g wheel xundao
          sed -E -i '/^#\s*%wheel.*NOPASSWD/{s/^#\s*//}' /etc/sudoers
          chmod 777 -R .
          runuser -u xundao -- bash -c "makepkg -s -f --noconfirm"
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: archiso
      #     path: out/

